version: '2'

services:
  dante:
    build: 
      context: .
      args:
        SOCKET_USER: "${SOCKET_USER}"
        SOCKET_PASSWORD: "${SOCKET_PASSWORD}"
    ports:
    - "${SOCKET_PORT}:1080"
    restart: always
    volumes:
    - ./sockd.conf:/etc/sockd.conf